added hts support

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -867,6 +867,8 @@ Optional Packages:
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-bamtools=PATH    specify directory containing the bamtools library
                           (http://github.com/pezmaster31/bamtools)
+  --with-hts=PATH         specify directory containing the HTS library
+                          (https://github.com/samtools/htslib)
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -4330,35 +4332,7 @@ fi;
 if test "$with_bamtools" -a -d "$with_bamtools"; then
     bamtools_ldflags="-Wl,-rpath,$with_bamtools/lib -L$with_bamtools/lib -Wl,-rpath,$with_bamtools/lib/bamtools -L$with_bamtools/lib/bamtools"
     bamtools_include="-I$with_bamtools/include -I$with_bamtools/include/bamtools"
-fi
-
-# Only fail on warnings when the --enable-development flag is passed into configure
-# Check whether --enable-development or --disable-development was given.
-if test "${enable_development+set}" = set; then
-  enableval="$enable_development"
-
-fi;
-if test "$enable_development"; then
-    fail_on_warning="-Werror"
-fi
-
-# Set compiler flags.
-AM_CXXFLAGS="-g -std=c++11 -Wall -Wextra $fail_on_warning -Wno-unknown-pragmas"
-
-CXXFLAGS="-O3"
-
-CFLAGS="-O3"
-
-CPPFLAGS="$CPPFLAGS $bamtools_include"
-
-LDFLAGS="$bamtools_ldflags $LDFLAGS -L."
-
-
-# We always need to specify to link in bamtools and ahocorasick
-LIBS="$LIBS -lbamtools -lahocorasick"
-
-
-# Make sure the bamtools headers can be found
+    # Make sure the bamtools headers can be found
 
 for ac_header in api/BamReader.h
 do
@@ -4512,6 +4486,207 @@ echo "$as_me: error: The bamtools library must be installed (http://github.com/p
 fi
 
 done
+
+fi
+
+
+# Check whether --with-hts or --without-hts was given.
+if test "${with_hts+set}" = set; then
+  withval="$with_hts"
+
+fi;
+
+if test "$with_hts" -a -d "$with_hts"; then
+    hts_ldflags="-Wl,-rpath,$with_hts -L$with_hts"
+    hts_include="-I$with_hts"
+else
+    ## hts_ldflags="-Wl,-rpath ./htslib-1.1 -L ./htslib-1.1"
+    hts_ldflags="-L ./htslib-1.1"
+    hts_include="-I htslib-1.1"
+fi
+
+
+# Only fail on warnings when the --enable-development flag is passed into configure
+# Check whether --enable-development or --disable-development was given.
+if test "${enable_development+set}" = set; then
+  enableval="$enable_development"
+
+fi;
+if test "$enable_development"; then
+    fail_on_warning="-Werror"
+fi
+
+# Set compiler flags.
+AM_CXXFLAGS="-g -std=c++11 -Wall -Wextra $fail_on_warning -Wno-unknown-pragmas"
+
+CXXFLAGS="-O3"
+
+CFLAGS="-O3"
+
+CPPFLAGS="$CPPFLAGS $bamtools_include $hts_include"
+
+LDFLAGS="$bamtools_ldflags $hts_ldflags $LDFLAGS -L."
+
+
+# We always need to specify to link in bamtools and ahocorasick
+LIBS="$LIBS -lbamtools -lahocorasick htslib-1.1/libhts.a -lpthread"
+
+
+# Make sure the bamtools headers can be found
+
+for ac_header in htslib/hts.h
+do
+as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+else
+  # Is the header compilable?
+echo "$as_me:$LINENO: checking $ac_header usability" >&5
+echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <$ac_header>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_cxx_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_header_compiler=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6
+
+# Is the header present?
+echo "$as_me:$LINENO: checking $ac_header presence" >&5
+echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <$ac_header>
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_cpp conftest.$ac_ext\"") >&5
+  (eval $ac_cpp conftest.$ac_ext) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null; then
+  if test -s conftest.err; then
+    ac_cpp_err=$ac_cxx_preproc_warn_flag
+    ac_cpp_err=$ac_cpp_err$ac_cxx_werror_flag
+  else
+    ac_cpp_err=
+  fi
+else
+  ac_cpp_err=yes
+fi
+if test -z "$ac_cpp_err"; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+rm -f conftest.err conftest.$ac_ext
+echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
+echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    (
+      cat <<\_ASBOX
+## --------------------------------------- ##
+## Report this to jwala@broadinstitute.org ##
+## --------------------------------------- ##
+_ASBOX
+    ) |
+      sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+echo "$as_me:$LINENO: checking for $ac_header" >&5
+echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6
+if eval "test \"\${$as_ac_Header+set}\" = set"; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  eval "$as_ac_Header=\$ac_header_preproc"
+fi
+echo "$as_me:$LINENO: result: `eval echo '${'$as_ac_Header'}'`" >&5
+echo "${ECHO_T}`eval echo '${'$as_ac_Header'}'`" >&6
+
+fi
+if test `eval echo '${'$as_ac_Header'}'` = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+_ACEOF
+
+else
+  { { echo "$as_me:$LINENO: error: The HTS library must be installed (https://github.com/samtools/htslib). You can specify its path with the --with-hts=PATH option" >&5
+echo "$as_me: error: The HTS library must be installed (https://github.com/samtools/htslib). You can specify its path with the --with-hts=PATH option" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+done
+
 
 
           ac_config_files="$ac_config_files Makefile"
